server:
  port=9875
camera:
  hk: rtsp://user:pass@ip:554/Streaming/tracks/101?starttime=20260413T120000Z&endtime=20260413T121000Z
  dh: rtsp://user:pass@ip:554/cam/playback?channel=1&starttime=2024_04_13_12_00_00&endtime=2024_04_13_13_00_00
aliyun:
  oss:
    endpoint: https://oss-cn-beijing-youzheng-d01-a.ops.2020yzcloud.cn/     # ????
    access-key-id: woLBmYcHyTUmcliD
    access-key-secret: 4PFQc60NSg2MMIREbwqMNSQOwUOpB9
    bucket-name: oss-zhxf-app-web-1